version: "3.7"

secrets:
  PSQL_REMOTE_HOST:
    external: true
  PSQL_USERNAME:
    external: true
  PSQL_DBNAME:
   external: true
  PGPASSWORD:
    external: true
 
services:
  pg_dump-to-google_sdk:
    image: thestevenbell/pg_dump-to-google_sdk:latest
    secrets:
      - PSQL_REMOTE_HOST
      - PSQL_USERNAME
      - PSQL_DBNAME
      - PGPASSWORD

