version: "3.7"

secrets:
  PSQL_REMOTE_HOST:
    external: true
  PSQL_USERNAME:
    external: true
  PSQL_DBNAME:
   external: true
  PGPASSWORD:
    external: true
  PSQL_REMOTE_HOST_PORT:
    external: true
  PSQL_SCHEMA:
    external: true
  GCS_BUCKET_NAME:
    external: true
  GCLOUD_SCV_ACCOUNT_CREDENTIALS_FILE.json:
    external: true

services:
  pg_dump-to-google_gcs:
    image: thestevenbell/pg_dump-to-google_sdk:latest
    deploy:
      restart_policy:
        condition: none
    environment:
      PSQL_REMOTE_HOST_FILE: /run/secrets/PSQL_REMOTE_HOST
      PSQL_REMOTE_HOST_PORT_FILE: /run/secrets/PSQL_REMOTE_HOST_PORT
      PSQL_USERNAME_FILE: /run/secrets/PSQL_USERNAME
      PSQL_DBNAME_FILE: /run/secrets/PSQL_DBNAME
      PGPASSWORD_FILE: /run/secrets/PGPASSWORD
      PSQL_SCHEMA_FILE: /run/secrets/PSQL_SCHEMA
      GCS_BUCKET_NAME_FILE: /run/secrets/GCS_BUCKET_NAME
      GOOGLE_APPLICATION_CREDENTIALS: run/secrets/GCLOUD_SCV_ACCOUNT_CREDENTIALS_FILE.json
    secrets:
      - PSQL_REMOTE_HOST
      - PSQL_USERNAME
      - PSQL_DBNAME
      - PGPASSWORD
      - PSQL_REMOTE_HOST_PORT
      - PSQL_SCHEMA
      - GCS_BUCKET_NAME
      - GCLOUD_SCV_ACCOUNT_CREDENTIALS_FILE.json