#!/bin/sh

DATETIME=`date "+%Y%m%d-%H%M%S"`

PSQL_REMOTE_HOST=$(cat ${PSQL_REMOTE_HOST_FILE})

PSQL_USERNAME=$(cat ${PSQL_USERNAME_FILE})

PSQL_DBNAME=$(cat ${PSQL_DBNAME_FILE})

PGPASSWORD=$(cat ${PGPASSWORD_FILE})

PSQL_REMOTE_HOST_PORT=$(cat ${PSQL_REMOTE_HOST_PORT_FILE})

PSQL_SCHEMA=$(cat ${PSQL_SCHEMA_FILE})

echo $PSQL_REMOTE_HOST:$PSQL_REMOTE_HOST_PORT:$PSQL_DBNAME:$PSQL_USERNAME:$PGPASSWORD > ~/.pgpass

chmod 0600 ~/.pgpass

FILE=backup-$DATETIME

pg_dump -U $PSQL_USERNAME -h $PSQL_REMOTE_HOST -p $PSQL_REMOTE_HOST_PORT -d $PSQL_DBNAME -n $PSQL_SCHEMA -Ft > $FILE.tar

exit 0


